select * from job_history
select * from employees

-- INNER JOIN

SELECT E.F_NAME,E.L_NAME, JH.START_DATE
FROM EMPLOYEES as E 
INNER JOIN JOB_HISTORY as JH 
ON E.EMP_ID=JH.EMPL_ID 
WHERE E.DEP_ID ='5';

-- LEFT JOIN

SELECT E.EMP_ID, E.L_NAME, E.DEP_ID, D.DEP_NAME
FROM EMPLOYEES AS E 
LEFT OUTER JOIN DEPARTMENTS AS D 
ON E.DEP_ID=D.DEPT_ID_DEP;

-- FULL OUTER JOIN
SELECT E.F_NAME, E.L_NAME, D.DEP_NAME
FROM EMPLOYEES AS E
LEFT OUTER JOIN DEPARTMENTS AS D
ON E.DEP_ID = D.DEPT_ID_DEP

UNION

SELECT E.F_NAME, E.L_NAME, D.DEP_NAME
FROM EMPLOYEES AS E
RIGHT OUTER JOIN DEPARTMENTS AS D
ON E.DEP_ID=D.DEPT_ID_DEP

-- EXERCISES

SELECT E.F_NAME, E.L_NAME, JH.START_DATE, D.DEP_NAME
FROM EMPLOYEES as E 
INNER JOIN JOB_HISTORY as JH 
ON E.EMP_ID=JH.EMPL_ID 
INNER JOIN DEPARTMENTS as D 
ON E.DEP_ID=D.DEPT_ID_DEP
WHERE E.DEP_ID ='5';


SELECT E.EMP_ID, E.L_NAME, E.B_DATE, D.DEP_NAME
FROM EMPLOYEES as E
LEFT JOIN DEPARTMENTS as D
ON E.DEP_ID=D.DEPT_ID_DEP
WHERE E.B_DATE < '1980/01/01';

SELECT E.L_NAME, D.DEPT_ID_DEP, D.DEP_NAME, E.SEX
FROM EMPLOYEES as E
LEFT JOIN DEPARTMENTS as D
ON E.DEP_ID=D.DEPT_ID_DEP
WHERE E.SEX = 'M'
UNION
SELECT E.L_NAME, D.DEPT_ID_DEP, D.DEP_NAME, E.SEX
FROM EMPLOYEES as E
RIGHT JOIN DEPARTMENTS as D
ON E.DEP_ID=D.DEPT_ID_DEP
WHERE E.SEX = 'M';